dependencies:
  - name: service-account
    version: 0.4.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: artifactory
    version: 9.4.5
    repository: https://charts.jfrog.io/
  - name: ocp-route
    version: 0.3.0
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
  - name: tool-config
    version: 0.8.1
    repository: https://ibm-garage-cloud.github.io/toolkit-charts/
